name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Smoke tests daily at 10:08 AM
    - cron: "10 11 * * *"
    # Sanity tests every 2 days at 10:08 AM
    - cron: "10 11 */2 * *"

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.checkout.outputs.path }}
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall -r requirements.txt

  setup-web:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Install Chrome & Chromedriver
        uses: browser-actions/setup-chrome@v1

  run-smoke-tests:
    runs-on: ubuntu-latest
    needs: setup-web
    if: github.event_name == 'schedule'  # only run on scheduled runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Smoke Tests
        run: |
          mkdir -p results
          python -m robot -d results --include smoke tests/web
          ls -l results

      - name: Upload Smoke Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results
          path: results/

  run-sanity-tests:
    runs-on: ubuntu-latest
    needs: setup-web
    if: github.event_name == 'schedule'  # only run on scheduled runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Sanity Tests
        run: |
          mkdir -p results
          python -m robot -d results --include sanity tests/web
          ls -l results

      - name: Upload Sanity Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sanity-test-results
          path: results/
