name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Smoke tests daily at 12:00 AM
    - cron: "0 0 * * *"
    # Sanity tests every 2 days at 1:00 AM
    - cron: "0 1 */2 * *"

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  setup-web:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chrome & Chromedriver
        uses: browser-actions/setup-chrome@v1

  setup-android:
    runs-on: ubuntu-latest
    needs: setup-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android Emulator & SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64              # Must be x86_64 for Ubuntu cloud runner
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio
          disable-animations: true
          emulator-boot-timeout: 300
          script: |
            echo "Adding Android platform-tools to PATH"
            echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

            max_wait_seconds=900   # 15 minutes
            elapsed=0

            echo "Starting Android emulator..."
            emulator -avd test_avd -no-window -gpu swiftshader_indirect -noaudio &

            # Wait for emulator to appear
            while ! adb devices | grep -q emulator; do
              echo "Waiting for emulator to appear..."
              sleep 5
              elapsed=$((elapsed+5))
              if [ $elapsed -ge $max_wait_seconds ]; then
                echo "ERROR: Emulator did not appear in time"
                exit 1
              fi
            done

            EMULATOR_ID=$(adb devices | grep emulator | awk '{print $1}')
            echo "Emulator ID detected: $EMULATOR_ID"

            # Wait for device to be online and fully booted
            boot_completed=""
            elapsed=0
            while [ "$boot_completed" != "1" ] && [ $elapsed -lt $max_wait_seconds ]; do
              status=$(adb -s $EMULATOR_ID get-state 2>/dev/null || echo "offline")
              if [ "$status" = "device" ]; then
                boot_completed=$(adb -s $EMULATOR_ID shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' || echo "")
              else
                echo "Device offline, retrying..."
              fi
              sleep 5
              elapsed=$((elapsed+5))
            done

            if [ "$boot_completed" = "1" ]; then
              echo "Android Emulator is Ready!"
            else
              echo "ERROR: Emulator failed to boot or stayed offline"
              exit 1
            fi

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-android
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Smoke Tests
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        run: |
          mkdir -p results
          python -m robot -d results --include smoke tests/

      - name: Run Sanity Tests
        if: github.event_name == 'schedule' && github.event.schedule == '0 1 */2 * *'
        run: |
          mkdir -p results
          python -m robot -d results --include sanity tests/

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
