name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Smoke tests daily at 11:10 AM
    - cron: "10 11 * * *"
    # Sanity tests every 2 days at 11:10 AM
    - cron: "10 11 */2 * *"
  workflow_dispatch:  # optional manual trigger

# -----------------------
# WEB TESTS (on GitHub-hosted runner)
# -----------------------
jobs:
  checkout-code-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  install-dependencies-web:
    runs-on: ubuntu-latest
    needs: checkout-code-web
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall -r requirements.txt

  setup-web:
    runs-on: ubuntu-latest
    needs: install-dependencies-web
    steps:
      - name: Install Chrome & Chromedriver
        uses: browser-actions/setup-chrome@v1

  run-smoke-tests-web:
    runs-on: ubuntu-latest
    needs: setup-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Smoke Tests
        run: |
          mkdir -p results
          python -m robot -d results --include smoke tests/web
          ls -l results
      - name: Upload Smoke Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results-web
          path: results/

  run-sanity-tests-web:
    runs-on: ubuntu-latest
    needs: setup-web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Sanity Tests
        run: |
          mkdir -p results
          python -m robot -d results --include sanity tests/web
          ls -l results
      - name: Upload Sanity Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sanity-test-results-web
          path: results/

# -----------------------
# ANDROID TESTS (on self-hosted runner using local emulator)
# -----------------------
jobs:
  run-smoke-tests-android:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Android Emulator is Online
        run: |
          echo "Checking for online emulator..."
          ONLINE_DEVICE=$(adb devices | awk 'NR>1 && $2=="device"{print $1}')
          if [ -z "$ONLINE_DEVICE" ]; then
            echo "ERROR: No emulator/device is online. Aborting tests."
            exit 1
          else
            echo "Emulator online: $ONLINE_DEVICE"
          fi

      - name: Run Smoke Tests on Local Emulator
        run: |
          mkdir -p results
          python -m robot -d results --include smoke tests/android
          ls -l results

      - name: Upload Smoke Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-results-android
          path: results/

  run-sanity-tests-android:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Android Emulator is Online
        run: |
          echo "Checking for online emulator..."
          ONLINE_DEVICE=$(adb devices | awk 'NR>1 && $2=="device"{print $1}')
          if [ -z "$ONLINE_DEVICE" ]; then
            echo "ERROR: No emulator/device is online. Aborting tests."
            exit 1
          else
            echo "Emulator online: $ONLINE_DEVICE"
          fi

      - name: Run Sanity Tests on Local Emulator
        run: |
          mkdir -p results
          python -m robot -d results --include sanity tests/android
          ls -l results

      - name: Upload Sanity Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sanity-test-results-android
          path: results/
