name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Smoke tests daily at 12:00 AM
    - cron: "0 0 * * *"
    # Sanity tests every 2 days at 1:00 AM
    - cron: "0 1 */2 * *"

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  setup-web:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Install Chrome & Chromedriver
        uses: browser-actions/setup-chrome@v1

  setup-android:
    runs-on: ubuntu-latest
    needs: setup-web
    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android Emulator & SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          avd-name: test-emulator
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio
          disable-animations: true
          script: |
            echo "Starting Android Emulator"
            emulator -avd test-emulator -no-window -gpu swiftshader_indirect -noaudio &
            adb wait-for-device

            # Wait until Android is fully booted
            boot_completed=""
            until [ "$boot_completed" = "1" ]; do
              echo "Waiting for emulator to fully boot..."
              sleep 5
              boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r' || echo "")
            done

            echo "Android Emulator is ready!"

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-android
    steps:
      - name: Run Smoke Tests
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *'
        run: |
          mkdir -p results
          python -m robot -d results --include smoke tests/

      - name: Run Sanity Tests
        if: github.event_name == 'schedule' && github.event.schedule == '0 1 */2 * *'
        run: |
          mkdir -p results
          python -m robot -d results --include sanity tests/

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/
